give @s cb:summon_spirit_upgrade
give @s cb:tentacle_sword
give @s cb:red_orb
give @s cb:xp_viole
give @s cb:kraken_scale_helmet
give @s cb:kraken_scales
give @s cb:kraken_scale_chestplate
give @s cb:xp_viole_4
give @s cb:xp_viole_5
give @s cb:xp_viole_1
give @s cb:xp_viole_2
give @s cb:xp_viole_3
give @s cb:orb_of_absorption_2
give @s cb:orb_of_regeneration_3
give @s cb:orb_of_regeneration_2
give @s cb:orb_of_regeneration
give @s cb:orb_of_absorption_3
give @s cb:kraken_scale_leggings
give @s cb:orb_of_absorption_1
give @s cb:kraken_scales_boots
give @s cb:orb_of_resistance
give @s cb:orb_of_speed
give @s cb:orb_of_resistance_2
give @s cb:orb_of_fire_immunity
give @s cb:orb_of_speed_3
give @s cb:orb_of_speed_2
give @s cb:orb_of_resistance_3
give @s cb:chestplate_of_heavens
give @s cb:main_dark_staff
give @s cb:yeti_fur
give @s cb:yeti_fur_helmet
give @s cb:frost_dagger
give @s cb:frost_viole
give @s cb:yeti_fur_leggings
give @s cb:yeti_fur_boots
give @s cb:pheonix_wings
give @s cb:yeti_fur_chestplate
give @s cb:kitsune_fur
give @s cb:krakens_fang
give @s cb:pheonix_heart
give @s cb:pheonix_blade
give @s cb:kitsune_claws
give @s cb:crimson_viole
give @s cb:pheonix_blade_skin_dvsb
give @s cb:xp_viole_6
give @s cb:kitsune_tails
give @s cb:wooden_bat
give @s cb:raw_goblin_meat
give @s cb:cooked_goblin_meat
give @s cb:iron_spiked_bat
give @s cb:centaur_hooves
give @s cb:raw_orc_meat
give @s cb:cooked_orc_meat
give @s cb:centaur_axe
give @s cb:iron_hooved_boots
give @s cb:hooved_yeti_fur_boots
give @s cb:hooved_kraken_scales_boots
give @s cb:hooved_chainmai_boots
give @s cb:hooved_gold_boots
give @s cb:hooved_diamond_boots
give @s cb:hooved_netherite_boots
give @s cb:hooved_leather_boots
give @s cb:horned_beer
give @s cb:vampiric_viole
give @s cb:cooked_minotaur_meat
give @s cb:raw_minotaur_meat
give @s cb:minotaur_horn
give @s cb:vampire_blood
give @s cb:mutated_spiderweb
give @s cb:toxic_viole
give @s cb:vampire_heart
give @s cb:vampiric_greatsword
give @s cb:toxic_spear
give @s cb:quest_book
give @s cb:webshooter
give @s cb:archanoweave
give @s cb:dark_staff_1
give @s cb:frost_staff
give @s cb:staff_of_crimson_flames
give @s cb:dark_staff_2
give @s cb:staff_of_azure_flames
give @s cb:kraken_poison_shooter
